language: python

sudo: false

notifications:
   email: false

#For Pypandoc can work, pandoc needs to be installed
addons:
  apt_packages:
    - pandoc
    
python:
  - 3.5
  
before_install:
  - pip install -U pip
#  - python -c \"from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');\" # To install pandoc
#  - export PATH=~/bin:$PATH

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
#  - python setup.py check --restructuredtext -s  # # Checking readme.rst formatting
#  - python setup.py checkdocs  # Checking readme.rst formatting
#  - travis_retry python setup.py develop

# command to run tests
script:
#  - python -m unittest tests.test_pyprime  # Basic way to see if the test are working
  - coverage run -m unittest tests.test_pyprime
#  - coverage run -m unittest discover -s tests/ # to run all tests of test folder
#  - coverage run --source=app setup.py test
#  - coverage run --source setup.py -m py.test # to be run with pytest
  - coverage report -m


  
#branches:
#  only:
#    - master
    
after_success:
  - pip install nprime
  - codecov
  - echo "Success!"
