language: python
sudo: false
python:
  - "3.5"
  
before_install:
- "pip install -U pip"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: 
  - "python src/examples.py"
  
branches:
  only:
    - master
    
after_success:
  - echo "Success!"