language: python

sudo: false

notifications:
   email: false
    
python:
  - 3.5
  
before_install:
  - pip install -U pip
  - python setup.py install

# command to install dependencies
install:
  - pip install -r requirements.txt
#  - travis_retry python setup.py develop

# command to run tests
script:
#  - python -m unittest tests.test_pyprime  # Basic way to see if the test are working
  - coverage run -m unittest tests.test_pyprime
#  - coverage run -m unittest discover -s tests/ # to run all tests of test folder
#  - coverage run --source=app setup.py test
#  - coverage run --source setup.py -m py.test # to be run with pytest
  - coverage report -m


  
#branches:
#  only:
#    - master
    
after_success:
  - codecov
  - echo "Success!"
