language: python

sudo: false

notifications:
   email: false

#For Pypandoc can work, pandoc needs to be installed
addons:
  apt_packages:
    - pandoc

python:
  - 3.5

env:
  global:
    secure: UkXMWiCMn2B4deXOVISAEAKjMm+KgPN+HGicPHNoMqo+h09WBUX081F+AW1eab06NWgDiGB6h+2lAsPbcmVtQ7Xu1mHGrIT6EU7iFMAvG7qwAdTD8npJNoGKlCxzy1R2iN74MBVMp+QpBAdgz9Xu147WQfinfy38RJW5Nspz/Kpte3QII0VITlCp2il9wRxKe4/tWVg8sUEHfzbJdJNvuAwjOPV6o5dHA6uKfbPFQ02qHMJKb1pimwrj4bRi35Ssk6ysYqdfDqveqtqBwlfZZhnfxrqz0uCkl9/9KRi2VupGnsbT7gzehsVLs99wrWGVL5rztmLEJ4D29nEkXSCLj6OVC8eXrTw29HuDS28IWSZerrVTAlPlyWQ+vuWk1K9WX3x+Li7tiKjallUMDP4B6VBFJxEtxqBO5pDBtAKRe8M8UC26ZkLSz6wA1bS1D1sLycvyL7iVh1bbu/ExF+FhUKm0RcJJ+gQxIgK0V/xMkduyv9JB9jebarh4LDSCriykTAg+nw06iLZuaOsU6XVr5zMC449kphxe0Fh67AnMS46qm1wf75X7LwmqPyQBUa+3Y9a/3BScWITXqw5bqY9IyOrQ6s3pG8r9WwaIle46PAqOzfYEZdL1xI9N6NWnvbDET33G5/IE0eJiIKnOsQHQDBuWwOzAnQDcNYUL0x/WQaE=

before_install:
  - pip install -U pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# commands to run tests
script:
  - coverage run --source=nprime -m unittest tests.test_pyprime
  - coverage xml # For Codacy

deploy:
  provider: pypi
  user: sylhare
  password:
    secure: h60Fn0vqYbAQP24h/AdTKoqxxgtSrHPtZaRo5r7g87HQbPie741ZvB2olNYm4RjRKLaFgA0gZdCsPmN1LhXEIfVtKZGql7E1Rb1feKCMu+uXnQ0yC5kd+JGuhiceZCR6k8sBsZplDmHXeHDG1ZQT0FsorHniM1uxxIGhfZuB62F23dGR7Go+j62tnLD779UzegaNn6vcWFfPoWwQRVhSONHaGzP+2QNxzRhDSQ8Vo2ABYPIQCueTHsdhkaDS38hzMY7dSBRRkxRLMDXzVs4ZxU4pb0hkvoHbGzpkdiCq5QR94HxuWqwxIWD4z0PkFL/bGG9AEb3QLbvgJgvCt+6Y/ZaPG1IP/4gqDr8GaZ1YbjoSpa6AZd4U2usm2gNFwyQnINkk2kXgj++3pcLB4K6VnGf8jdM3JNGVsneGanSkcXtfJtOFlyfKVcvEbJ9/AlsLr/3ZmfSaGTa4/dfBEnOEAN7MkQCGVuPLmc9E8mzW4evTmICe8nr2so9HcQnFhXnvlWTc5mc/j3xnvp6PKmewQQCO98LAebLvbugM9qFUokIk1bmsyexZC66kJV1ksDQlPRXrVSsLNf/9mYl1MNtOykDr5gr3arTYD3iPui798ZUzNL2i3tiAakMP0WAlsgPHKpvCnCeaPu1oWlEp6i2VA5AXQ1c3LQ/5MWWcIXQ1QcA=

after_success:
  - pip install nprime
  - codecov
  - python-codacy-coverage -r coverage.xml
