# https://circleci.com/docs/2.0/hello-world/
version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5.3
     steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r requirements/dev.txt
       - run: python src/examples.py